version: 2
sources:
  - name: RAW_SOURCE
    description: This is RAW_TEST Database Source Tables used for creating STANDARD_TEST Layer
    database: RAW
    tables:
      - name: CUSTOMER
      - name: ORDERS
  - name: STAGE
    description: This is RAW_TEST Database Source Tables used for creating STANDARD_TEST Layer
    database: RAW
    tables:
      - name: CUSTOMER
      - name: ORDERS